### ISSUE TITLE
Add gamepad control capability

### ISSUE THREAD

**Issue by birdybro** [wizzomafizzo/MiSTer_GamesMenu#1]
Currently all of the face buttons either switch between ok and exit, or they press the "enter" equivalent. Not sure if there is any way to address this the same way the other TUI style scripts do it.

**Comment by wizzomafizzo** [comment]
Ahhh I know! It's so annoying! I don't know of a way to make this particular widget work without the controller pressing space. But that would be very unintuitive even if a patch were accepted in menu

Do you know of any scripts in particular that work around it? I can check it out. Otherwise I may just make my own fake checklist widget

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/Scripts_MiSTer/blob/master/ini_settings.sh - this one does but it's a different TUI interface entirely

**Comment by birdybro** [comment]
Nice, thanks! :)
