### ISSUE TITLE
MiSTer SAM initiated while the script was running, all listings keeps fully regenerating

### ISSUE THREAD

**Issue by Drakonas** [wizzomafizzo/MiSTer_GamesMenu#6]
Hello,
Is there a way to clear out the database? The script was abruptly halted when SAM started in the middle of the script, changing the core in the process.

The Game Boy core was running at the time. After it ran, even though all the items were toggled on, everything after the Game boy was found off, and now it fully generates every core after Game Boy (including Game Boy), every time the script is ran.

Thank you for your time.

**Comment by wizzomafizzo** [comment]
I left you a message in Discord too. Don't worry, it sounds normal, as long as when you check the menu everything looks ok. The script would have just completed as normal after SAM kicked in. If you want to be absolutely sure then you can just delete the _Games folder on your SD card which is effectively clearing out the database. But I'd recommend not doing that because it's practically the same as just re-running the script

It is normal for it to take a while scanning all your files every single run. There's no choice but to do that since there's no other way to tell everything is up to date. Every scan after the first one is not rewriting any files though, just reading them. You won't be wearing out your SD card

**Comment by Drakonas** [comment]
Understood. Might have been placebo. Thank you.
